#!/usr/bin/env python3

import sqlite3, sys
import micro_buildd_conf as conf

def main(argv):
    if len(argv) != 3:
        print("""Usage: make_binnmu package version changelog
e.g. make_binnmu r-cran-ade4 1.7-15-1 "Rebuild against r-api-4.0"
""")
        sys.exit(1)
    pkg = argv[0]
    ver = argv[1]
    changelog = argv[2]

    db = sqlite3.connect(conf.database_path)
    db.execute("""UPDATE states
        SET BinNMUVersion = CASE WHEN BinNMUVersion IS NULL THEN 1 ELSE BinNMUVersion + 1 END,
            BinNMUChangelog = :BinNMUChangelog,
            State = "BD-Uninstallable",
            BDUninstallableReasons = "unevaluated"
        WHERE Package == :Package AND Version == :Version AND State == "Installed";
        """, {'Package': argv[0], 'Version': argv[1], 'BinNMUChangelog': argv[2] })
    db.commit()

if __name__ == '__main__':
    main(sys.argv[1:])
